### PR TITLE
#2 Design Web App

### PR DESCRIPTION
**Pull request by j0narch3r**
PR for initial styles for https://assembly.com/pay-it-forward/bounties/2

### CODE REVIEW

**Comment by whatupdave** [comment]
Hey this looks like cool stuff. How do we get to the pages to check it out? I booted up the app but there's no routes for this.

**Comment by bshyong** [comment]
`http://localhost:3000/pages/instructions`?

**Comment by sirwolfgang** [comment]
@whatupdave @bshyong The routes are currently based on `/page/:id`, `:id` being the name of the page.

**Comment by sirwolfgang** [comment]
_Intructions_
image

_Selection_
image

_Pledge_
image

_Authorization_
image

_Challenge_
image

**Comment by whatupdave** [comment]
Rad, thanks for the previews!

**Comment by j0narch3r** [comment]
1) How do I reply to a specific comment?
2) @whatupdave  happy to take any feedback once it's staged and you can click through it (as far as we've gotten, anyway).

**Pull request merged**
